---
title: Inside Retail
timezone: UTC
collections:
  carousel:
    title: Carousel
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
analytics: 
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Nullam id dolor id nibh ultricies vehicula ut id elit.
domain: http://insideretail.com
company: i2i Events Group
email: info@insideretail.com
facebook: https://www.facebook.com/insideretail
instagram: https://www.instagram.com/insideretail
twitter: https://twitter.com/insideretail
google: "UA-80072725-1"
logo: "/assets/img/layout/logo.svg"
per_page: 12