---
title: Inside Retail
timezone: UTC
collections:
  carousel:
    title: Carousel
    output: true
  blog_categories:
    title: Categories
    output: true
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: articles/:title/
    layout: post
    excerpt-image: 
    excerpt-text: 
    hero-video: 
    hero-image: 
    hero-text: 
    hero-quote: 
    hero-cite: 
    length: 
    is-top: 
    top-image: 
- scope:
    path: ''
    type: blog_tags
  values:
    layout: tag
- scope:
    path: ''
    type: blog_categories
  values:
    layout: category
permalink: pretty
gems:
- jekyll-seo-tag
- jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi leo risus,
  porta ac consectetur ac, vestibulum at eros. Morbi leo risus, porta ac consectetur
  ac, vestibulum at eros. Nullam id dolor id nibh ultricies vehicula ut id elit.
domain: http://insideretail.com
company: i2i Events Group
email: info@insideretail.com
facebook: https://www.facebook.com/insideretail
instagram: https://www.instagram.com/insideretail
twitter: https://twitter.com/insideretail
google: UA-80072725-1
logo: "/assets/img/layout/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
